name: years_in_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc:
  animated_splash_screen: ^1.0.1+2
  equatable: 
  dartz:
  intl:
  connectivity:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:

  uses-material-design: true

  assets:
    - assets/splash.png
    

